# Generated by Django 5.1.15 on 2026-05-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
